# Generated by Django 4.2.3 on 2023-08-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('course', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('course', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('profile_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgapp.studentdetails')),
            ],
        ),
    ]
