# Generated by Django 4.2.3 on 2023-08-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0002_studentdetails_image_removed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='image_removed',
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
